# -*- coding: utf-8 -*-
"""train_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USqW96A0Oai3R-ItTZyy2lGDcQhPOkfa
"""

!pip install ultralytics opencv-python pandas kagglehub

import kagglehub

path = kagglehub.dataset_download("imtkaggleteam/microplastic-dataset-for-computer-vision")

print("Dataset path:", path)

import shutil

dst = "/content/dataset"

shutil.copytree(path, dst, dirs_exist_ok=True)

import os

print("Main:", os.listdir("/content/dataset"))
print("Train sample:", os.listdir("/content/dataset/train")[:5])
print("Valid sample:", os.listdir("/content/dataset/valid")[:5])

import pandas as pd
import os

csv_path = "/content/dataset/train/_annotations.csv"
label_folder = "/content/dataset/train/labels"

os.makedirs(label_folder, exist_ok=True)

df = pd.read_csv(csv_path)

for filename in df['filename'].unique():
    rows = df[df['filename'] == filename]

    txt_path = os.path.join(label_folder, filename.replace(".jpg", ".txt"))

    with open(txt_path, "w") as f:
        for _, row in rows.iterrows():
            w = row['width']
            h = row['height']

            xmin = row['xmin']
            ymin = row['ymin']
            xmax = row['xmax']
            ymax = row['ymax']

            x_center = ((xmin + xmax) / 2) / w
            y_center = ((ymin + ymax) / 2) / h
            box_width = (xmax - xmin) / w
            box_height = (ymax - ymin) / h

            f.write(f"0 {x_center} {y_center} {box_width} {box_height}\n")

import pandas as pd
import os

csv_path = "/content/dataset/valid/_annotations.csv"
label_folder = "/content/dataset/valid/labels"

os.makedirs(label_folder, exist_ok=True)

df = pd.read_csv(csv_path)

for filename in df['filename'].unique():
    rows = df[df['filename'] == filename]

    txt_path = os.path.join(label_folder, filename.replace(".jpg", ".txt"))

    with open(txt_path, "w") as f:
        for _, row in rows.iterrows():
            w = row['width']
            h = row['height']

            xmin = row['xmin']
            ymin = row['ymin']
            xmax = row['xmax']
            ymax = row['ymax']

            x_center = ((xmin + xmax) / 2) / w
            y_center = ((ymin + ymax) / 2) / h
            box_width = (xmax - xmin) / w
            box_height = (ymax - ymin) / h

            f.write(f"0 {x_center} {y_center} {box_width} {box_height}\n")

import shutil
import os

def organize(folder):
    img_folder = os.path.join(folder, "images")
    os.makedirs(img_folder, exist_ok=True)

    for file in os.listdir(folder):
        if file.endswith(".jpg"):
            shutil.move(
                os.path.join(folder, file),
                os.path.join(img_folder, file)
            )

organize("/content/dataset/train")
organize("/content/dataset/valid")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/data.yaml
# 
# path: /content/dataset
# 
# train: train/images
# val: valid/images
# 
# names:
#   0: Microplastic

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.train(
    data="/content/data.yaml",
    epochs=50,
    imgsz=640
)

from ultralytics import YOLO

model = YOLO("runs/detect/train/weights/best.pt")

model("/content/dataset/valid/images", show=True)

